# Behaviour

## At home
Molly is a very good girl at home and will spend most of the day between her walks asleep. She generally won't bark at passers-by, doorbells etc (and we sternly tell her "no barking" if she ever does). She does like to sit in a comfy spot and at home she is allowed on the couch but she knows she has to be "on your blanket". She likes a little snuggle in the morning and evening and she has an inbuilt alarm clock set to 5pm for evening walks. She doesn't counter surf or chew things (apart from her toys).   

## Being left alone
Molly is fine to be left alone in the home and will usualy just sleep on our bed if we are out during the day. As a puppy she would get anxious and whine when we left her alone but we got through that by following some common advice, which we recommend:

* Give her some time to get comfortable in a new space before leaving her alone
* Make sure she is toileted, fed, and exercised before leaving
* Don't make a fuss when leaving, just say "Molly, mind the house"
* Don't make a fuss when returning - we will usually completely ignore her for a minute before saying hello. 

## With other people

Molly is generally great with other people and will sometimes want to stop and say hello to people on walks. If she gets too excited she might try to jump up to say hello (we say "no jumping"). She is always very gentle with children. 

## Outside


