# Food

## Regular Meals 

Molly's main food is [Hill's Science Diet Sensitive Stomach & Skin Adult Dog Food](https://www.petbarn.com.au/science-diet-sensitive-stomach-skin-adult-dog-food?sku=137412). She eats one cup in the morning (usually about 8-9am) and one cup in the evening (ususally about 7-8pm).

In her morning meal we include 1ml of [4cyte joint supplement](https://au.4cyte.global/dogs/4cyte-epiitalis-forte-for-dogs/). 

Sometimes we will add small amounts of other food to Molly's kibble, for example if we are having banana with our breakfast we will give here a few slices too. Foods Molly enjoys like this include:

* Banana
* Blueberries
* Watermelon
* Tuna (spring water cans)  
* Pumpkin
* Peas
* Carrots
* Egg
* Yogurt 
* Cheese
* Small dash of milk

## Treats

We usually use [vitapet milky sticks](https://vitapet.com/au/products/milky-sticks/) for training treats. Molly will enjoy all sorts of dog treats but please only in moderation. For example, we would give her two vita sticks a day, broken into to small pieces for training and walking.  

## Allergies/Food issues

* Molly loves chicken but too much can give her diarrhoea
* Molly loves bones (e.g. uncooked beef bones) but chewing on these for too long can give her an upset stomach (constipation/diarrhoea)
