# Health

## Vet

**Vet**

Molly's vet is Hurlstone Park Veterinary Hospital
* 02 9558 4181
* [hurlstoneparkveterinaryhospital.com.au](https://hurlstoneparkveterinaryhospital.com.au/)
* 739 New Canterbury Road, Dulwich Hill, NSW 2203
* hpvets@hurlstoneparkvet.com.au


## Vaccination
Molly is fully up-to-date with annual vaccinations (C7). She receives her vaccines annually in June. 

## Fleas and Worms

Molly takes a monthly tablet for fleas, worms, ticks etc. She takes [NexGard Spectra](https://www.petbarn.com.au/nexgard-spectra-for-dogs-15-1-30kg?sku=134736) (for 15-30kg dogs) on the 13th of every month.

## Desexing

Molly is desexed. 

## Hip Dysplasia

Molly has hip dysplasia. This is generally doesn't cause any issues and is kept in check by limiting the extent of her physical exercise sessions. In her morning meal we include 1ml of [4cyte joint supplement](https://au.4cyte.global/dogs/4cyte-epiitalis-forte-for-dogs/). Molly will get lame, stiff, or sore if she is given too much physical exercise. 

## Grooming

Molly is fastidious with her own grooming and will usually spend time every morning and evening grooming and "cleaning" her paws. Her coat is non-shed and can get matted easily so we pick out any burrs etc straight away and comb her regularly, especially her ears which are prone to knots otherwise. 
